server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-customer
          uri: lb://service-customer
          predicates:
            - Path=/api/customers/**

        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/api/products/**


eureka:
  client:
    serviceUrl: 
      defaultZone: http://service-discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true